### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by twang2218**
Signed-off-by: Tao Wang <twang2218@gmail.com>

### CODE REVIEW

**Comment by twang2218** [comment]
This is another approach for building docker image. Not like PR #24 , this Dockerfile is using the new multi-stage building feature which available since Docker 17.05, the separation of golang compilation and final image construction will decrease the docker image size significantly. Only binary matters will be put to the final image.

```bash
$ docker images prometheus-nats-exporter
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
prometheus-nats-exporter   latest              2ef8939b67ef        About an hour ago   7.79MB
```

As shown above, the final image is quite small, just below 8MB. The final image is `FROM scratch` and only contains the `prometheus-nats-exporter` binary.

## Test

Build the image by:

```bash
docker build -t prometheus-nats-exporter .
```

Then test this image via docker-compose, here is the `docker-compose.yml`:

```yml
version: '3'
services:
  nats:
    image: nats:0.9.6
    ports:
      - "4222:4222"
    command: -c gnatsd.conf -m 8222
  prometheus-nats-exporter:
    image: prometheus-nats-exporter
    command: -varz "http://nats:8222"
  prometheus:
    image: prom/prometheus:v1.7.1
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "mypassword"
    ports:
      - "3000:3000"
```

The stack is followed the walkthrough document, https://github.com/nats-io/prometheus-nats-exporter/blob/master/walkthrough/README.md

The `prometheus.yml` is quite simple, one thing should be noticed is the address for export should be the service name, `prometheus-nats-exporter`:

```yml
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'NATS Servers'

scrape_configs:
  - job_name: 'NATS-servers'
    static_configs:
      - targets: ['prometheus-nats-exporter:7777']

```

After `docker-compose up -d`, then the Grafana can be visit at http://localhost:3000. When adding the prometheus source, using `http://prometheus:9090` as the URL, then it should works as same as the `walkthrough` document.

screenshot 2017-07-13 03 40 29

Here is what the final result in Grafana after the `nats-bench` test.

**Comment by laugimethods** [comment]
That's great!
Indeed, multi-stage building can be very helpful.
However, there is still a drawback: [Multi-Stage builds NOT YET AVAILABLE on docker hub]( https://github.com/docker/hub-feedback/issues/1039)

**Comment by ColinSullivan1** [comment]
Thank you for the contribution!  I'll check this out and get back to you.  We may want to wait until multi-stage builds are supported.

**Comment by trystanj** [comment]
@ColinSullivan1 have you had a chance to look at this, now that multi-stage builds are supported? I'd love to use an officially supported version rather than one I've custom-built!

**Comment by ColinSullivan1** [comment]
@trystanj , I'll take a look!  Thanks!

**Comment by ColinSullivan1** [comment]
@trystanj @twang2218 , I think we should start with an image containing only gnatsd and the prometheus-nats-exporter - users may want to run their prometheus servers elsewhere, and may want to use a different visualization tool - wdyt?

**Comment by trystanj** [comment]
@ColinSullivan1 I like @twang2218 's approach - a single image with just the exporter. It makes a lot of sense to have a container doing just one thing. For example in Kubernetes, I'm using this approach along with https://github.com/pires/kubernetes-nats-cluster in a pod. So the pod has 1 gnats container and 1 prometheus-nats-exporter image (but they're a single "unit" - a pod). It allows for some nice composition. Some people may want one instance of the exporter, or may not want it at all, like you mentioned.

**Comment by trystanj** [comment]
@ColinSullivan1 Have you had a chance to play with this some more?

**Comment by jebbench** [comment]
It would be great if this could be merged and pushed to Docker hub; saves us from having to maintain our own copy of it.

**Comment by ColinSullivan1** [comment]
@trystanj , @jebbench , Apologies for the delay, I'll revisit this.  I'd like to get an official release cut before pushing a docker image.  There are a few security related features that need to be added first, but it's in my plans to get this done in the next month.

**Comment by jebbench** [comment]
Any progress on this?

**Comment by ColinSullivan1** [comment]
@twang2218 , Thank you for the contribution!

**Comment by trystanj** [comment]
Amazing, thank you! Looking forward to getting the image pushed so we can start using this!

Thanks @ColinSullivan1 & @twang2218!

**Comment by ColinSullivan1** [comment]
I'm ironing out a few things, will release, and then should get the image pushed soon!

**Pull request merged**
